FROM jenkins/jenkins:lts-jdk21

USER root

# Cài Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    usermod -aG docker jenkins

# (tuỳ chọn) Cài git nếu chưa có
RUN apt-get install -y git

USER jenkins
