services:
    jenkins:
        image: jenkins/jenkins:lts-jdk21
        build:
            context: .
            dockerfile: Dockerfile.jenkins
        container_name: jenkinsLTS
        user: root
        restart: unless-stopped
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - JAVA_OPTS=-Duser.timezone=Asia/Ho_Chi_Minh

volumes:
    jenkins_home:
        external: true
